# Generated by Django 3.2.9 on 2022-06-25 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220625_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), db_index=True, default=list, size=None),
        ),
    ]
